-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;

DROP TABLE IF EXISTS public."bible_words_references" CASCADE;
DROP TABLE IF EXISTS public."translation" CASCADE;
DROP TABLE IF EXISTS public."google_sheet" CASCADE;
DROP TABLE IF EXISTS public."bible_text" CASCADE;

DROP TABLE IF EXISTS public."strongs_numbers" CASCADE;
DROP TABLE IF EXISTS public."book" CASCADE;
DROP TABLE IF EXISTS public."translation_status" CASCADE;
DROP TABLE IF EXISTS public."language" CASCADE;



CREATE TABLE IF NOT EXISTS public.bible_text
(
    id bigserial NOT NULL,
    language_id integer NOT NULL,
    book_id integer NOT NULL,
    chapter_num integer NOT NULL,
    verse_num integer NOT NULL,
    verse_text text COLLATE pg_catalog."default",
    CONSTRAINT bible_text_pkey PRIMARY KEY (id),
    CONSTRAINT bible_text_book_id_chapter_num_verse_num_key UNIQUE (book_id, chapter_num, verse_num)
);

CREATE TABLE IF NOT EXISTS public.strongs_numbers
(
    strong_id bigint NOT NULL,
    strongs_number character(5) COLLATE pg_catalog."default" NOT NULL,
    d_strong character(1) COLLATE pg_catalog."default",
    original_word character varying(128) COLLATE pg_catalog."default" NOT NULL,
    english_translation character varying(128) COLLATE pg_catalog."default" NOT NULL,
    long_text text COLLATE pg_catalog."default",
    short_text text COLLATE pg_catalog."default",
    step_united_reason character varying(32),
    step_type character varying(32),
    transliteration character varying(128) COLLATE pg_catalog."default",
    pronunciation character varying(128),
    CONSTRAINT "StrongsNumbers_pkey" PRIMARY KEY (strong_id),
    CONSTRAINT strong_numbers_unique UNIQUE (strongs_number, d_strong)
);

CREATE TABLE IF NOT EXISTS public.book
(
    id integer NOT NULL,
    usfm_name character varying(64) COLLATE pg_catalog."default" NOT NULL,
    osis_name character varying(64) COLLATE pg_catalog."default",
    full_name character varying(128) COLLATE pg_catalog."default",
    CONSTRAINT book_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.language
(
    id integer NOT NULL,
    name character varying(128),
    iso_639_1 character(2) NOT NULL,
    iso_639_2 character(3) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.google_sheet
(
    sheet_id integer NOT NULL,
    id character varying(128) NOT NULL,
    name character varying(64) NOT NULL,
    first_strong character(6) NOT NULL,
    last_strong character(6) NOT NULL,
    translation_language integer NOT NULL,
    last_updated timestamp without time zone NOT NULL,
    PRIMARY KEY (sheet_id),
    UNIQUE (id)
);

CREATE TABLE IF NOT EXISTS public.translation
(
    strong_id bigint NOT NULL,
    sheet_id integer NOT NULL,
    update_date timestamp without time zone NOT NULL,
    updater_name character varying(128),
    updater_email character varying(128),
    status_id integer,
    translated_gloss character varying(128),
    translated_text text,
    transliteration character varying(128),
    PRIMARY KEY (strong_id, sheet_id, update_date)
);

CREATE TABLE IF NOT EXISTS public.translation_status
(
    id integer NOT NULL,
    status character(16) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.bible_words_references
(
    strong_id bigint NOT NULL,
    language_id integer NOT NULL,
    gloss character varying(64) COLLATE pg_catalog."default" NOT NULL,
    "references" text,
    CONSTRAINT bible_words_references_pkey PRIMARY KEY (strong_id, language_id, gloss)
);

ALTER TABLE IF EXISTS public.bible_text
    ADD FOREIGN KEY (language_id)
    REFERENCES public.language (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.bible_text
    ADD FOREIGN KEY (book_id)
    REFERENCES public.book (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.google_sheet
    ADD FOREIGN KEY (translation_language)
    REFERENCES public.language (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.translation
    ADD FOREIGN KEY (sheet_id)
    REFERENCES public.google_sheet (sheet_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.translation
    ADD FOREIGN KEY (status_id)
    REFERENCES public.translation_status (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.translation
    ADD FOREIGN KEY (strong_id)
    REFERENCES public.strongs_numbers (strong_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.bible_words_references
    ADD FOREIGN KEY (strong_id)
    REFERENCES public.strongs_numbers (strong_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.bible_words_references
    ADD FOREIGN KEY (language_id)
    REFERENCES public.language (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;